language: c

sudo: required

matrix:
  include:
    - env:
      - APACHE_VERSION="2.2.x"
    - env:
      - APACHE_VERSION="2.4.x"

before_install:
  - .travis/before_install.sh

install:
  - ./autogen.sh
  - ./configure
  - make
  - .travis/install.sh

before_script:
  - .travis/before_script.sh

script:
  - ./tests/test.sh
